
[Damage-Module]
	#The purpose of the damage module is to remove the invulnerability ticks after an entity is damaged to better suit gameplay where entities are going to be ignoring too much damage if left unchecked. Disabling will nullify every feature listed under this module.
	damageModuleEnabled = false
	#Some entities or damage sources rely on damage ticks to time their attacks. In these cases, we want to let them initiate i-frames.
	#entityBlacklist default: ["minecraft:slime","minecraft:ender_dragon","minecraft:magma_cube"]
	entityBlacklist = ["minecraft:slime", "minecraft:ender_dragon", "minecraft:magma_cube"]
	#damagesourceBlacklist default: ["lava","inFire","cactus","inWall","hotFloor","lightningBolt","sweetBerryBush","outOfWorld"]
	damagesourceBlacklist = ["lava", "inFire", "cactus", "inWall", "hotFloor", "lightningBolt", "sweetBerryBush", "outOfWorld"]
	#In order to prevent spam attacks, a minimum threshold of attack strength can be set before an attack can deal damage. Default: 0.75
	minimumAttackStrength = 0.75
	#Whether or not a player is allowed to even swing if the threshold is not met. Default: false
	allowNonFullStrengthAttacks = false
	#Global multiplier to all knockback. Default: 1.0
	globalKnockbackMultiplier = 1.0

[Durability-Module]
	#The purpose of the durability module is to rework how durability damage is applied to better emulate an rpg setting.  Disabling will nullify every feature listed under this module.
	durabilityModuleEnabled = true
	#Whether or not tools and armor should take regular durability damage while in use. Default: false
	takeDurabilityDamage = true
	#The percent of durability damage equipment should take on player dying. Set to 0 to disable. Default: 0.15 (15%)
	durabilityLostOnDeath = 0.10
	#An additional constant amount of damage taken on death. This makes items with a high max durability degrade relatively slower. Set to 0 to disable. Default: 25
	additionalDurabilityLostOnDeath = 20
	#What type of gear is damaged upon death. Default: ALL
	#Allowed Values: ALL, TOOLS, ARMOR
	durabilityGearType = "ALL"

[XP-Module]
	#The purpose of the xp module is to rework how experience is dropped on a player's death by creating a souls-like xp catalyst instead. Disabling will nullify every feature listed under this module.
	xpModuleEnabled = true
	#Whether or not the keepInventory gamerule will prevent the player from losing xp Default: false, meaning even though you keep your items, your xp is still dropped.
	respectKeepInventory = false
	#Whether or not the player who dropped the xp is the only player allow to collect the xp. Default: true
	onlyAllowOwnerPickup = true
	#Global multiplier to experience amount gained. Default: 1.0
	globalXpMultiplier = 1.0

[Enchantment-Module]
	#The purpose of the enchantment module is to mystify enchantments and add an additional challenge to game by obscuring the description of enchanted and cursed items found through looting. Disabling will nullify every feature listed under this module.
	enchantmentModuleEnabled = true
	#Whether or not armor should be automatically identified when equipped. Default: true
	identifyOnEquip = true
	#Whether or not unidentified items can be identified by interacting with an enchanting table. Default: true
	identifyOnEnchantingTable = true
	#Whether or not the enchanting table's functionality should be disabled, making looting or trading the only way to get enchanted items. Default: false
	disableEnchantingTable = false

