
[entities]

	[entities.moth]
		#How many moths required to destroy a torch - Disabled if set to 0
		#Range: > 0
		moths_to_destroy_torch = 5

		[entities.moth.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 10
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 2
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["regions_unexplored:cold_deciduous_forest", "minecraft:forest", "regions_unexplored:silver_birch_forest", "regions_unexplored:flooded_plains", "regions_unexplored:old_growth_boreal_forest", "terralith:alpine_grove", "minecraft:mangrove_swamp", "terralith:ice_marsh", "ars_nouveau:archwood_forest", "regions_unexplored:giant_bayou", "regions_unexplored:deciduous_forest", "terralith:cloud_forest", "regions_unexplored:smouldering_woodland", "regions_unexplored:temperate_grove", "minecraft:dark_forest", "regions_unexplored:blackwood_forest", "regions_unexplored:golden_boreal_forest", "regions_unexplored:fen", "minecraft:grove", "goodending:oak_hammock_forest", "regions_unexplored:boreal_forest", "regions_unexplored:mauve_hills", "regions_unexplored:cherry_hills", "regions_unexplored:autumnal_maple_forest", "minecraft:flower_forest", "regions_unexplored:orchard", "minecraft:swamp", "minecraft:birch_forest", "regions_unexplored:wooded_steppe", "minecraft:old_growth_birch_forest", "goodending:marshy_swamp", "regions_unexplored:maple_forest", "regions_unexplored:bayou", "terralith:orchid_swamp"]

			[entities.moth.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 3.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.hidebehind]

		[entities.hidebehind.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 20
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 2
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["regions_unexplored:cold_deciduous_forest", "minecraft:forest", "regions_unexplored:silver_birch_forest", "regions_unexplored:old_growth_boreal_forest", "terralith:alpine_grove", "ars_nouveau:archwood_forest", "regions_unexplored:deciduous_forest", "terralith:cloud_forest", "regions_unexplored:smouldering_woodland", "regions_unexplored:temperate_grove", "minecraft:dark_forest", "regions_unexplored:blackwood_forest", "regions_unexplored:golden_boreal_forest", "minecraft:grove", "goodending:oak_hammock_forest", "regions_unexplored:boreal_forest", "regions_unexplored:mauve_hills", "regions_unexplored:cherry_hills", "regions_unexplored:autumnal_maple_forest", "minecraft:flower_forest", "regions_unexplored:orchard", "minecraft:birch_forest", "regions_unexplored:wooded_steppe", "minecraft:old_growth_birch_forest", "regions_unexplored:maple_forest"]
			#Enables biome based variant selection. This will make this entity choose variants tailored to the biome they spawn in (Only applies to natural spawns)
			biome_based_variants = true

			[entities.hidebehind.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.wisp]
		#Allows the entity to despawn freely when no players are nearby, like vanilla monsters do
		can_despawn = false
		#Chance of wisp being hostile (soul stealer). Chance is a percentage out of 100. 0 is never, 100 is always
		#Range: 0.0 ~ 100.0
		hostile_chance = 20.0

		[entities.wisp.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 13
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 3
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["regions_unexplored:cold_deciduous_forest", "minecraft:forest", "regions_unexplored:silver_birch_forest", "regions_unexplored:flooded_plains", "regions_unexplored:old_growth_boreal_forest", "terralith:alpine_grove", "minecraft:mangrove_swamp", "terralith:ice_marsh", "ars_nouveau:archwood_forest", "regions_unexplored:giant_bayou", "regions_unexplored:deciduous_forest", "terralith:cloud_forest", "regions_unexplored:smouldering_woodland", "regions_unexplored:temperate_grove", "windswept:snowy_chestnut_forest", "windswept:chestnut_forest", "minecraft:dark_forest", "regions_unexplored:blackwood_forest", "regions_unexplored:golden_boreal_forest", "regions_unexplored:fen", "minecraft:grove", "goodending:oak_hammock_forest", "regions_unexplored:boreal_forest", "regions_unexplored:mauve_hills", "regions_unexplored:cherry_hills", "regions_unexplored:autumnal_maple_forest", "minecraft:flower_forest", "regions_unexplored:orchard", "dreamland:jeweled_forest", "minecraft:swamp", "minecraft:birch_forest", "regions_unexplored:wooded_steppe", "minecraft:old_growth_birch_forest", "goodending:marshy_swamp", "regions_unexplored:maple_forest", "regions_unexplored:bayou", "terralith:orchid_swamp"]

			[entities.wisp.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.hirschgeist]
		#Allows the entity to despawn freely when no players are nearby, like vanilla monsters do
		can_despawn = false

		[entities.hirschgeist.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = false
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 2
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["regions_unexplored:cold_deciduous_forest", "minecraft:forest", "regions_unexplored:silver_birch_forest", "regions_unexplored:old_growth_boreal_forest", "terralith:alpine_grove", "ars_nouveau:archwood_forest", "regions_unexplored:deciduous_forest", "terralith:cloud_forest", "regions_unexplored:smouldering_woodland", "regions_unexplored:temperate_grove", "minecraft:dark_forest", "regions_unexplored:blackwood_forest", "regions_unexplored:golden_boreal_forest", "minecraft:grove", "goodending:oak_hammock_forest", "regions_unexplored:boreal_forest", "regions_unexplored:mauve_hills", "regions_unexplored:cherry_hills", "regions_unexplored:autumnal_maple_forest", "minecraft:flower_forest", "regions_unexplored:orchard", "minecraft:birch_forest", "regions_unexplored:wooded_steppe", "minecraft:old_growth_birch_forest", "regions_unexplored:maple_forest"]

			[entities.hirschgeist.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

	[entities.zotzpyre]

		[entities.zotzpyre.spawning]
			#Enables natural spawning - More info on these options: https://minecraft.fandom.com/wiki/Spawn#Java_Edition
			spawn_naturally = true
			#The spawn weight compared to other entities (typically between 6-20)
			#Range: 1 ~ 9999
			spawn_weight = 36
			#Minimum amount of entities in spawned groups
			#Range: 1 ~ 9999
			minimum_group_size = 1
			#Maximum amount of entities in spawned groups - Must be greater or equal to min value
			#Range: 1 ~ 9999
			maximum_group_size = 1
			#Enter biome IDs. Supports modded biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
			spawn_biomes = ["terralith:alpine_highlands", "minecraft:snowy_taiga", "terralith:scarlet_mountains", "regions_unexplored:silver_birch_forest", "regions_unexplored:canadian_forest", "regions_unexplored:flooded_plains", "regions_unexplored:fungal_fen", "regions_unexplored:wooded_arid_mountains", "regions_unexplored:autumnal_mixed_taiga", "terralith:amethyst_canyon", "terralith:siberian_taiga", "regions_unexplored:bamboo_forest", "terralith:siberian_grove", "minecraft:beach", "regions_unexplored:frozen_forest", "minecraft:dark_forest", "regions_unexplored:blackwood_forest", "regions_unexplored:mauve_hills", "minecraft:meadow", "regions_unexplored:autumnal_maple_forest", "regions_unexplored:orchard", "regions_unexplored:rainforest", "terralith:gravel_desert", "terralith:rocky_jungle", "minecraft:swamp", "terralith:volcanic_peaks", "terralith:rocky_mountains", "regions_unexplored:wooded_steppe", "minecraft:old_growth_birch_forest", "regions_unexplored:grassy_beach", "regions_unexplored:tropics", "minecraft:jungle", "regions_unexplored:icy_desert", "regions_unexplored:lush_hills", "terralith:gravel_beach", "ars_nouveau:archwood_forest", "regions_unexplored:giant_bayou", "terralith:snowy_badlands", "terralith:jungle_mountains", "regions_unexplored:smouldering_woodland", "terralith:fractured_savanna", "regions_unexplored:roofed_eucalyptus_forest", "terralith:haze_mountain", "regions_unexplored:cherry_hills", "minecraft:flower_forest", "terralith:caldera", "terralith:shield", "minecraft:birch_forest", "terralith:volcanic_crater", "regions_unexplored:icy_heights", "regions_unexplored:maple_forest", "minecraft:frozen_peaks", "regions_unexplored:mountains", "terralith:yellowstone", "minecraft:jagged_peaks", "terralith:alpine_grove", "terralith:snowy_maple_forest", "terralith:forested_highlands", "regions_unexplored:spires", "minecraft:windswept_hills", "terralith:tropical_jungle", "regions_unexplored:deciduous_forest", "terralith:cloud_forest", "minecraft:windswept_gravelly_hills", "terralith:bryce_canyon", "regions_unexplored:sparse_redwoods", "terralith:rocky_shrubland", "regions_unexplored:fen", "minecraft:grove", "terralith:ashen_savanna", "minecraft:stony_peaks", "regions_unexplored:gravel_beach", "regions_unexplored:pine_forest", "minecraft:snowy_slopes", "terralith:emerald_peaks", "regions_unexplored:cold_deciduous_forest", "minecraft:forest", "minecraft:old_growth_pine_taiga", "minecraft:lush_caves", "terralith:white_cliffs", "terralith:basalt_cliffs", "regions_unexplored:old_growth_boreal_forest", "terralith:amethyst_rainforest", "minecraft:mangrove_swamp", "regions_unexplored:towering_cliffs", "regions_unexplored:highland_fields", "terralith:wintry_forest", "minecraft:snowy_plains", "terralith:ice_marsh", "regions_unexplored:eucalyptus_forest", "regions_unexplored:chalk_cliffs", "regions_unexplored:redwoods", "regions_unexplored:temperate_grove", "minecraft:bamboo_jungle", "minecraft:snowy_beach", "regions_unexplored:golden_boreal_forest", "regions_unexplored:old_growth_rainforest", "regions_unexplored:pine_slopes", "terralith:lush_valley", "regions_unexplored:arid_mountains", "goodending:oak_hammock_forest", "regions_unexplored:boreal_forest", "minecraft:sparse_jungle", "minecraft:windswept_forest", "regions_unexplored:cold_boreal_forest", "minecraft:taiga", "goodending:marshy_swamp", "regions_unexplored:bayou", "terralith:orchid_swamp"]

			[entities.zotzpyre.spawning.spawn_costs]
				#Whether to use spawn costs in spawning or not
				use_spawn_costs = false
				#Cost to spawning algorithm per entity spawned
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				cost_per_spawn = 1.0
				#Maximum cost the spawning algorithm can accrue for this entity
				#Range: 4.9E-324 ~ 1.7976931348623157E308
				maximum_cost_per_biome = 10.0
				#Enter biome IDs to use these costs in. Supports modded biomes. An empty list will use spawn_biomes https://minecraft.fandom.com/wiki/Biome#Biome_IDs
				spawn_cost_biomes = []

