#If true, entities will be affected by gravity.
doEntityGravity = true
#Do gravity for mobs, players etc.
doLivingEntityGravity = true
acidRainBurns = true
doOxygen = true
#Do sound suppression in orbit dimensions. If it gets annoying, you can turn it off.
doSpaceMuffler = true
oxygenTankSize = 500
hammerDurability = 64
giveAstroduxAtSpawn = false
oxygenBarXOffset = 0
oxygenBarYOffset = 0
energyBarXOffset = 0
energyBarYOffset = 0
orbitGravity = 3.259999990463257
oxygenDamage = 2
freezeDamage = 1
heatDamage = 2
acidRainDamage = 3
allowFlagImages = true
#A list of planets that should be disabled. This is a comma-separated list of planet ids.
disabledPlanets = ""
#Prevents stuff like gravity and oxygen checks in the overworld as that's normally not used in Ad Astra. enable if you're making an addon or something that transforms the overworld into some sort of planet.
avoidOverworldChecks = true
oxygenBarScale = 1.0
energyBarScale = 1.0
#Enable/Disable lunarian and lunarian wandering trader's default trades. Apply to lunarian spawned after this value changed.
enabledLunarianDefaultTrades = true

[spawning]
	spawnCorruptedLunarians = true
	spawnStarCrawlers = true
	spawnMartianRaptors = true
	spawnMoglers = true
	spawnSulfurCreepers = true
	spawnLunarianWanderingTrader = true

[spaceSuit]
	spaceSuitTankSize = 1000
	netheriteSpaceSuitTankSize = 2000
	netheriteSpaceSuitHasFireResistance = true
	#The speed when flying forward.
	jetSuitSpeed = 0.8
	#The speed when idle flying up.
	jetSuitUpwardsSpeed = 0.5
	jetSuitEnergyPerTick = 60
	jetSuitTankSize = 4000
	jetSuitMaxEnergy = 1000000
	enableJetSuitFlight = true
	jetSuitProtectionMultiplier = 1
	jetSuitArmorToughness = 6
	spawnJetSuitParticles = true
	#Custom hand rendering may interfere with Shaders
	renderCustomFirstPersonHand = true

[vehicles]
	#The velocity to trigger a vehicle explosion while falling.
	fallingExplosionThreshold = 4.9E-324
	#How much the explosion should be multiplied by when the vehicle has fallen.
	fallingExplosionMultiplier = 0.699999988079071
	gravity = 4.9E-324
	#Should the camera move in 3rd person in the rocket and lander for a better view?
	moveCameraInVehicle = true

	[vehicles.lander]
		boosterThreshold = 4.9E-324
		boosterSpeed = 0.1

	[vehicles.rover]
		explodeRoverInLava = true
		fuelPerSecond = 10
		turnSpeed = 3.0
		maxTurnSpeed = 6.0
		deceleration = 0.8999999761581421
		minSpeed = 1.401298464324817E-45
		maxSpeed = 0.30000001192092896
		tankSize = 3000

	[vehicles.rocket]
		atmosphereLeave = 600
		countDownTicks = 200
		acceleration = 0.005
		maxSpeed = 0.5
		entitiesBurnUnderRocket = true
		tankSize = 3000
		fuelLaunchCost = 3000
		efficientFuelLaunchCost = 1000
		takeDamageInRocket = true

[coalGenerator]
	maxEnergy = 10
	energyPerTick = 1

[compressor]
	maxEnergy = 9000
	energyPerTick = 10

[fuelRefinery]
	maxEnergy = 9000
	energyPerTick = 30
	tankSize = 3000

[oxygenLoader]
	maxEnergy = 9000
	energyPerTick = 10
	tankSize = 3000

[solarPanel]
	maxEnergy = 1
	energyMultiplier = 1.0

[waterPump]
	maxEnergy = 9000
	energyPerTick = 10
	tankSize = 6000
	transferPerTick = 100
	deleteWaterBelowWaterPump = true

[energizer]
	maxEnergy = 2000000
	energyPerTick = 170

[cryoFreezer]
	maxEnergy = 30000
	energyPerTick = 3000
	tankSize = 3000

[oxygenDistributor]
	maxEnergy = 20000
	fluidConversionEnergyPerTick = 5
	tankSize = 6000
	#How many blocks the distributor can distribute oxygen in. Be careful increasing this number, as it can reduce server performance significantly. If you are adamant about increasing this value, consider increasing the Oxygen Loader refresh ticks so the server is not constantly checking thousands of blocks.
	#Range: 1 ~ 50000
	maxBlockChecks = 2000
	#How often the oxygen loader checks if the structure is sealed. Performing this operation too often can kill server TPS, so be wary.
	#Range: 0 ~ 500
	refreshTicks = 60
	#Increases the oxygen requirements as the distributor covers more blocks.
	oxygenMultiplier = 1.0
	#Increases the energy requirements as the distributor covers more blocks.
	energyMultiplier = 3.0

