
["basic options"]
	"Enable weight for fish? Useful for fishing competitions" = true
	"Should fish be added as compostables for the composter/worm farm? (Based on fish, or weight if enabled)" = true
	"Should Aquaculture fish be able to be used to breed cats & ocelots?" = true
	"Enable debug mode? (Enables additional logging)" = false
	"Show Fillet recipes in JEI?" = true

	["basic options"."Amount of Message In A Bottle messages"]
		#Range: 0 ~ 255
		" Used to add additional custom messages" = 29

["neptunium options"]
	"Enable recipes for Neptunium items?" = false
	"Enable recipes for Neptunium armor?" = false
	#Should Neptune's bounty be added as fishing loot? Very rare.
	"Add Neptune's Bounty as loot?" = true

