
[general]
	#Toggle Health bars for mobs
	toogle = true
	#Render health bar only when the mob is visible
	onvisible = true
	#Show health points on bars. Note that not every type of the bars can show the hp
	show_hp = true
	#Show the Name above the mobs
	show_name = true
	#Show bars only when a mob is aggressive
	on_aggro = true
	#
	#List for the mobs that should not be displayed, put a comma (,) between the registered names!
	blacklist = "minecraft:wither, meetyourfight:swampjaw, meetyourfight:bellringer, meetyourfight:dame_fortuna, meetyourfight:rosalyne, twilightforest:alpha_yeti, twilightforest:lich, twilightforest:naga, twilightforest:snow_queen, undergarden:masticator, whisperwoods:hirschgeist, alexsmobs:void_worm, alexsmobs:void_worm_part, alexsmobs:void_worm_shot, alexsmobs:void_portal, alexsmobs:centipede_body, alexsmobs:centipede_tail, cataclysm:ignis, cataclysm:netherite_monstrosity, cataclysm:ender_guardian"

	#MobHealtBar
	[general.hpbar]
		#Health Bar Type
		#Range: 1 ~ 13
		type = 7
		#X Position
		#Range: > -2147483648
		x-pos = 0
		#Y Position
		#Range: > -2147483648
		y-pos = 0
		#Render Distance
		#Range: > 0
		render-distance = 1000
		#Scale Nametag
		#Range: 0.0 ~ 1.7976931348623157E308
		scale-name = 1.0
		#Scale Bar
		#Range: 0.0 ~ 1.7976931348623157E308
		scale-bar = 0.9
		#Scale Numbers
		#Range: 0.0 ~ 1.7976931348623157E308
		scale-nums = 1.0

