
#General settings for Molten Vents
[common]
	#The rarity of vents. The higher the number the rarer the vents. Default: 690
	ventRarity = 900
	#The depth of vents. When set below 10 the vents will stop generating immediately below the molten ore block, which is useful for specific cases such as when using the Stratospheric Expansion mod to prevent the vents from sticking through the bottom of the islands. Default: 100
	ventDepth = 60
	#When true, vents will only generate underwater. Vent depth is limited to a maximum of 80 when this setting is enabled. Default: false
	generateUnderwater = false
	#The name of the liquid that molten orestones will convert into orestones. Important: For modded liquids you must have the mod's technical id such as 'tconstruct' instead of 'Tinkers Construct'. Default: 'minecraft:lava'
	requiredLiquid = "minecraft:lava"
	#When true, orestone blocks will only replace liquid source blocks. This means that you will require a constant supply of liquid to generate orestones. If turned off, flowing blocks will be converted at a much slower rate. Default: true
	useSourceBlocks = true
	#The number of ticks to wait before flowing lava is converted to orestone, effective only if useSourceBlocks is set to false. Default: 300 (15 seconds) (0 - 1000)
	flowingConversionSpeed = 300
	#When true, vents will be filled with lava and decorated with Blackstone. Default: true
	fillWithLava = true

