
[behaviour]
	#This section determines the behaviour of the Weeping Angels - if you wish to ban a block from being interacted with by Weeping Angels, you will need to create a datapack and edit weeping_angels:no_breaking
	#Determines the range quantum locked entities will check if the player is looking in
	#Range: 1 ~ 100
	stalk_range = 65
	#If enabled alongside the mobGriefing gamerule, angels will interact with blocks that emit light
	block_breaking = true

[damage]
	#Hurt
	#Allowed Values: PICKAXE, PICKAXE_AND_GENERATOR, NONE, GENERATOR, ANYTHING
	hurt_type = "PICKAXE_AND_GENERATOR"

[teleporting]
	#Determines the range that a player can be teleported from their current location
	#Range: > 1
	teleport_range = 400
	#Determines the chance a player will be teleported
	#Range: 1 ~ 100
	teleport_chance = 10
	#A list of Dimensions that angels cannot teleport players to
	banned_dimensions = ["minecraft:the_end", "minecraft:the_nether", "the_bumblezone:the_bumblezone", "twilightforest:twilight_forest", "ad_astra:mars", "ad_astra:moon", "ad_astra:mercury", "ad_astra:venus", "ad_astra:glacio", "ad_astra:mars_orbit", "ad_astra:moon_orbit", "ad_astra:mercury_orbit", "ad_astra:venus_orbit", "ad_astra:glacio_orbit", "blue_skies:everbright", "blue_skies:everdawn", "undergarden:undergarden", "ae2:spatial_storage", "createteleporters:pocket_dimension", "deeperdarker:otherside", "ad_astra:earth_orbit", "createteleporters:corrupt_dimension", "mythicbotany:alfheim"]

