
#Default difficulty caps at 250
[general]
	#Disable/Enables the whole difficulty scaling of this mod. Requires a mc restart
	"Enable difficulty scaling" = true
	#Time in ticks for which the difficulty shouldnt increase at the beginning. One full minecraft day is 24000 ticks
	#Range: > 0
	"Difficulty Delay" = 0
	#Handles increase in difficulty regarding current difficulty.
	#Format is <minimum current difficulty>-<increase every 2400 ticks>
	#Example ["0-0.01","10-0.1","30-0"]
	#-> So the difficulty increases by 0.01 every 2400 ticks (->0.1 per mc day since a mc day has 24000 ticks) till it reaches a difficulty of 10.
	#Then it increases by 1 per mc day till it reaches 30 and then stops.
	"Difficulty Increase" = ["0-0.1", "250-0"]
	#Wether difficulty should only increase with at least one online players or not
	"Ignore Players" = false
	#If true will increase difficulty by the amount of time skipped. Else will only increase difficulty once.
	"Punish Time Skip" = false
	#Disable/Enable friendly fire for owned pets.
	FriendlyFire = false
	#Blacklist for pet you should't be able to give armor to. Pets from mods, which have custom armor already should be included here (for balancing reasons).
	"Pet Blacklist" = []
	#Treat pet blacklist as whitelist
	"Pet Whitelist" = false
	#Increase difficulty with time
	#Here untill its back as a gamerule
	"Difficulty toggle" = false
	#How the difficulty at a position is calculated. Supported values are: 
	#GLOBAL: Serverwide difficulty value
	#PLAYERMAX: Maximum difficulty of players in a 256 radius around the position
	#PLAYERMEAN: Average difficulty of players in a 256 radius around the position
	#Allowed Values: GLOBAL, PLAYERMAX, PLAYERMEAN
	"Difficulty type" = "PLAYERMEAN"

#Black/Whitelist for various stuff
[list]
	#Entities added here will be blacklisted from their assigned flags. Usage:
	#<entity registry name> or <namespace> followed by any of:
	#[ALL,ATTRIBUTES,ARMOR,HELDITEMS,BLOCKBREAK,USEITEM,LADDER,STEAL,GUARDIAN,PARROT,TARGETVILLAGER,NEUTRALAGGRO,REVERSE].
	#Having no flags is equal to ALL. Use REVERSE to reverse all flags. Some flags do nothing for certain mobs!
	#Examples (without <>):
	#<minecraft:sheep> (equal to minecraft:sheep|ALL) excludes sheeps from all modifications
	#<minecraft:sheep|REVERSE|ATTRIBUTES will> add sheep to attributes modification only
	#<minecraft:sheep|ATTRIBUTES> will add sheep to everything except attributes
	#<minecraft> blacklists all minecraft mobs from everything
	"Entity Configs" = ["cataclysm", "mutantmore:test_climber", "alexsmobs:froststalker", "tofucraft:tofufish", "alexsmobs:centipede_tail", "species:deepfish", "alexsmobs:snow_leopard", "alexsmobs:lobster", "alexsmobs:seagull", "biomemakeover:helmit_crab", "aquaculture:pink_salmon", "aquaculture:atlantic_herring", "alexsmobs:moose", "alexsmobs:seal", "productivebees:bumble_bee", "environmental:deer", "minecraft:glow_squid", "alexsmobs:shoebill", "irons_spellbooks:summoned_frog", "alexsmobs:roadrunner", "alexsmobs:laviathan", "minecraft:trader_llama", "upgrade_aquatic:goose", "productivebees:creeper_bee", "blue_skies:supporter_pet", "alexsmobs:endergrade", "minecraft:horse", "mutantmonsters:mutant_snow_golem", "productivebees:green_carpenter_bee", "aquaculture:muskellunge", "aquaculture:bayad", "blue_skies:jelly_drifter", "minecraft:llama", "twilightforest:raven", "aquaculture:bluegill", "alexsmobs:maned_wolf", "whisperwoods:moth", "minecraft:tadpole", "minecraft:dolphin", "upgrade_aquatic:immortal_jellyfish", "whisperwoods:hidebehind", "biomemakeover:scuttler", "environmental:yak", "alexsmobs:gelada_monkey", "alexsmobs:komodo_dragon", "blue_skies:azulfo", "alexsmobs:hammerhead_shark", "blue_skies:reindeer", "galosphere:spectator_vision", "minecraft:donkey", "alexsmobs:tiger", "biomemakeover:blightbat", "twilightforest:loyal_zombie", "upgrade_aquatic:box_jellyfish", "alexsmobs:grizzly_bear", "blue_skies:firefly", "environmental:duck", "quark:stoneling", "buzzier_bees:grizzly_bear", "friendsandfoes:moobloom", "friendsandfoes:copper_golem", "aquamirae:golden_moth", "minecraft:bee", "aquaculture:perch", "species:birt", "the_bumblezone:bee_queen", "alexsmobs:devils_hole_pupfish", "irons_spellbooks:summoned_polar_bear", "biomemakeover:toad", "cataclysm:the_baby_leviathan", "galosphere:sparkle", "alexsmobs:crocodile", "quark:toretoise", "deeperdarker:stalker", "infernalexp:warpbeetle", "galosphere:spectre", "productivebees:yellow_black_carpenter_bee", "aquaculture:jellyfish", "alexsmobs:rhinoceros", "cnb:lizard", "undergarden:brute", "minecraft:mooshroom", "alexsmobs:frilled_shark", "enderzoology:owl", "alexsmobs:bison", "minecraft:villager", "aquaculture:tuna", "alexsmobs:bald_eagle", "cnb:little_grebe", "blue_skies:snow_owl", "rottencreatures:hunter_wolf", "friendsandfoes:glare", "minecraft:axolotl", "botania:doppleganger", "alexsmobs:blobfish", "biomemakeover:lightning_bug", "galosphere:specterpillar", "productivebees:mason_bee", "friendsandfoes:tuff_golem", "alexsmobs:gorilla", "productivebees:hoarder_bee", "environmental:slabfish", "autumnity:snail", "aquaculture:blackfish", "undergarden:gloomper", "aquaculture:arapaima", "environmental:tapir", "infernalexp:glowsilk_moth", "alexsmobs:tusklin", "minecraft:strider", "undergarden:gwibling", "minecraft:parrot", "quark:crab", "aquamirae:spinefish", "productivebees:rancher_bee", "alexsmobs:cosmic_cod", "alexsmobs:underminer", "minecraft:wandering_trader", "aquaculture:carp", "productivebees:sweat_bee", "biomemakeover:mushroom_trader", "aquaculture:pacific_halibut", "infernalexp:basalt_giant", "productivebees:blue_banded_bee", "coldsnaphorde:frostycow", "ad_astra:lunarian", "minecraft:frog", "minecraft:iron_golem", "netherdepthsupgrade:lava_pufferfish", "netherdepthsupgrade:blazefish", "alexsmobs:kangaroo", "blue_skies:grittle_flatfish", "twilightforest:deer", "productivebees:nomad_bee", "botania:pixie", "cave_enhancements:cruncher", "alexsmobs:banana_slug", "dummmmmmy:target_dummy", "cnb:cindershell", "productivebees:ashy_mining_bee", "mythicbotany:alf_pixie", "biomemakeover:tadpole", "alexsmobs:mimic_octopus", "netherdepthsupgrade:bonefish", "aquaculture:boulti", "irons_spellbooks:wisp", "alexsmobs:hummingbird", "alexsmobs:bunfungus", "upgrade_aquatic:cassiopea_jellyfish", "upgrade_aquatic:flare", "biomemakeover:lightning_bug_alternate", "twilightforest:squirrel", "biomemakeover:rootling", "minecraft:mule", "takesapillage:clay_golem", "alexsmobs:crow", "friendsandfoes:mauler", "tofucraft:tofu_golem", "alexsmobs:flying_fish", "aquaculture:atlantic_cod", "tofucraft:tofunian", "alexsmobs:centipede_body", "aquaculture:synodontis", "hexerei:crow", "twilightforest:boar", "productivebees:configurable_bee", "minecraft:pufferfish", "aquaculture:starshell_turtle", "enlightened_end:dewcrawl", "alexsmobs:tarantula_hawk", "infernalexp:shroomloin", "twilightforest:dwarf_rabbit", "cnb:sporeling", "minecraft:fox", "aquaculture:smallmouth_bass", "alexsmobs:cachalot_whale", "minecraft:allay", "netherdepthsupgrade:obsidianfish", "alexsmobs:warped_toad", "minecraft:chicken", "alexsmobs:giant_squid", "blue_skies:horizofin_tunid", "irons_spellbooks:spectral_steed", "productivebees:leafcutter_bee", "upgrade_aquatic:pike", "alexsmobs:emu", "alexsmobs:cockroach", "aquaculture:minnow", "ad_astra:glacian_ram", "blue_skies:frost_spirit", "aquaculture:tambaqui", "buzzier_bees:moobloom", "goodending:firefly_swarm", "neapolitan:chimpanzee", "alexsmobs:flutter", "netherdepthsupgrade:glowdine", "netherdepthsupgrade:eyeball_fish", "cnb:minipad", "aquaculture:catfish", "blue_skies:municipal_monkfish", "balloonbox:balloon", "alexsmobs:terrapin", "aquamirae:luminous_jelly", "alexsmobs:capuchin_monkey", "cnb:cactem", "aquaculture:brown_shrooma", "alexsmobs:anaconda", "blue_skies:shade_monitor", "mutantmore:mutant_shulker_trap", "productivebees:digger_bee", "minecraft:polar_bear", "spirit:soul", "friendsandfoes:player_illusion", "dreamland:bumble_beast", "productivebees:dye_bee", "upgrade_aquatic:nautilus", "habitat:pooka", "aquaculture:brown_trout", "minecraft:pig", "minecraft:turtle", "aquaculture:red_shrooma", "blue_skies:crogre", "alexsmobs:alligator_snapping_turtle", "tofucraft:traveler_tofunian", "minecraft:sheep", "aquaculture:atlantic_halibut", "amodgus:amongus", "productivebees:cupid_bee", "netherdepthsupgrade:searing_cod", "minecraft:goat", "alexsmobs:rattlesnake", "minecraft:cod", "aquaculture:gar", "productivebees:neon_cuckoo_bee", "environmental:fennec_fox", "aquaculture:red_grouper", "alexsmobs:mantis_shrimp", "netherdepthsupgrade:wither_bonefish", "netherdepthsupgrade:soulsucker", "alexsmobs:raccoon", "goodending:woodpecker", "blue_skies:cosmic_fox", "alexsmobs:platypus", "minecraft:squid", "minecraft:skeleton_horse", "mutantmonsters:spider_pig", "twilightforest:tiny_bird", "alexsmobs:potoo", "enlightened_end:big_ringling", "minecraft:cow", "undergarden:dweller", "aquaculture:rainbow_trout", "tofucraft:tofucow", "mutantmore:mutant_shulker_turret", "alexsmobs:fly", "productivebees:lumber_bee", "dyenamics:sheep", "quark:shiba", "upgrade_aquatic:ululu", "alexsmobs:blue_jay", "whisperwoods:wisp", "blue_skies:charscale_moki", "alexsmobs:toucan", "minecraft:salmon", "upgrade_aquatic:lionfish", "alexsmobs:sea_bear", "tofucraft:tofupig", "undergarden:scintling", "twilightforest:quest_ram", "habitat:passerine", "minecraft:snow_golem", "netherdepthsupgrade:fortressgrouper", "alexsmobs:anteater", "alexsmobs:mudskipper", "alexsmobs:rain_frog", "alexsmobs:sugar_glider", "biomemakeover:glowfish", "rottencreatures:treasure_chest", "supplementaries:red_merchant", "environmental:zombie_deer", "minecraft:rabbit", "biomancy:flesh_blob", "aquaculture:piranha", "netherdepthsupgrade:magmacubefish", "productivebees:reed_bee", "aquaculture:box_turtle", "goodending:marsh", "alexsmobs:orca", "alexsmobs:leafcutter_ant", "irons_spellbooks:priest", "irons_spellbooks:dead_king_corpse", "infernalexp:blackstone_dwarf", "twilightforest:bighorn_sheep", "dreamland:opal_shell", "alexsmobs:mungus", "alexsmobs:jerboa", "minecraft:bat", "biomemakeover:stone_golem", "upgrade_aquatic:perch", "alexsmobs:spectre", "alexsmobs:cosmaw", "alexsmobs:catfish", "enlightened_end:xenon_bubble", "mutantmonsters:creeper_minion", "aquaculture:pollock", "alexsmobs:comb_jelly", "deeperdarker:shriek_worm", "blue_skies:sliv", "autumnity:turkey", "railways:conductor", "aquaculture:arrau_turtle", "cave_enhancements:dripstone_tortoise", "species:roombug", "alexsmobs:elephant", "cnb:lilytad", "aquaculture:capitaine", "infernalexp:glowsquito", "productivebees:collector_bee", "alexsmobs:gazelle", "productivebees:chocolate_mining_bee", "alexsmobs:skunk", "enlightened_end:helium_bubble", "minecraft:zombie_horse", "alexsmobs:sunbird", "biomemakeover:dragonfly", "environmental:koi", "cnb:end_whale", "blue_skies:stardust_ram", "alexsmobs:tasmanian_devil", "minecraft:cat", "alexsmobs:stradpole", "mutantmore:rodling", "blue_skies:gatekeeper", "deeperdarker:shattered", "mutantmore:concoction_w", "blue_skies:crystal_camel", "productivebees:farmer_bee", "productivebees:resin_bee", "minecraft:tropical_fish", "undergarden:minion", "bygonenether:wither_skeleton_horse", "ad_astra:lunarian_wandering_trader", "deeperdarker:sculk_snapper", "minecraft:ocelot", "twilightforest:penguin", "biomemakeover:owl", "the_bumblezone:beehemoth", "productivebees:quarry_bee", "minecraft:wolf", "minecraft:panda", "undergarden:mog"]
	#Any of the following 
	#[ATTRIBUTES, ARMOR, HELDITEMS, BLOCKBREAK, USEITEM, LADDER, STEAL, GUARDIAN, PARROT, TARGETVILLAGER, NEUTRALAGGRO]
	#added here will disable that feature completely.
	#E.g. ["GUARDIAN"] will disable the guardian feature
	"Flag Blacklist" = []
	#Treat ATTRIBUTES flags as whitelist
	"Attribute Whitelist" = false
	#Treat ARMOR flags as whitelist
	"Armor Equip Whitelist" = false
	#Treat HELDITEMS flags as whitelist
	"Held Equip Whitelist" = false
	#Treat BLOCKBREAK flags as whitelist
	"Breaker Whitelist" = false
	#Treat USEITEM flags as whitelist
	"Item Use Whitelist" = false
	#Treat LADDER flags as whitelist
	"Ladder Whitelist" = false
	#Treat STEAL flags as whitelist
	"Steal Whitelist" = false
	#Treat GUARDIAN flags as whitelist
	"Guardian Whitelist" = false
	#Treat PARROT flags as whitelist
	"Phantom Whitelist" = false
	#Treat TARGETVILLAGER flags as whitelist
	"Villager Whitelist" = false
	#Treat NEUTRALAGGRO flags as whitelist
	"Neutral Aggro Whitelist" = false

#Settings for mod integration
[integration]
	#Should the scaling health mods difficulty system be used instead of this ones. (Requires scaling health mod)
	"Use Scaling Health Mod" = true
	#If true and playerEx is installed will use the level from playerEx as difficulty
	"Use Player EX Mod" = false
	#If true and LevelZ is installed will use the the total skill level from LevelZ as difficulty
	"Use LevelZ Mod" = false

#Settings regarding custom ai for mobs
[ai]
	#Whitelist for blocks, which can be actively broken. 
	#Usage: <registry name;classname;tag;namespace> put "!" infront to exclude blocks
	#Note: If you include common blocks (like grass blocks) the pathfinding can have undesirable results.
	"Block Break Whitelist" = ["forge:glass", "forge:glass_panes", "minecraft:fence_gates", "forge:fence_gates", "minecraft:wooden_doors"]
	#Treat Block Whitelist as Blocklist
	"Breaklist as Blacklist" = false
	#Use the block breaking sound instead of a knocking sound
	Sound = false
	#Chance for a mob to be able to break blocks
	#Range: 0.0 ~ 1.0
	"Breaker Chance" = 0.0
	#Initial cooldown for block breaking mobs
	#Range: > 0
	"Breaker Initial Cooldown" = 120
	#Cooldown for breaking blocks
	#Range: > 0
	"Breaker Cooldown" = 20
	#If mobs should break blocks when not chasing a target
	"Idle Break" = false
	#Chance for a mob to be able to steal items from inventory blocks
	#Range: 0.0 ~ 1.0
	"Stealer Chance" = 0.0
	#Items which will be given to mobs who can break blocks. Empty list = no items. Syntax: id;weight
	#Note: Mobs can only break blocks if the tool they are holding can break the blocks
	"Breaking items" = ["minecraft:diamond_pickaxe;1", "minecraft:iron_axe;2"]
	#Should mobs be able to break block entities? Evaluated before the break list
	"Break BlockEntities" = false
	#Chance for neutral mobs to be aggressive
	#Range: 0.0 ~ 1.0
	"Neutral Aggressive Chance" = 0.05
	#List for of pairs containing which mobs auto target others. Syntax is [mob id]-[mob id] where second value is the target.
	# e.g. minecraft:zombie-minecraft:skeleton makes all zombies target skeletons
	"Auto Target List" = []
	#Difficulty at which mobs are able to break blocks
	#Range: 0.0 ~ 1.7976931348623157E308
	"Difficulty Break AI" = 0.0
	#Difficulty at which mobs are able to steal items
	#Range: 0.0 ~ 1.7976931348623157E308
	"Difficulty Steal AI" = 0.0
	#Chance for mobs to be able to summon an aquatic mount
	#Range: 0.0 ~ 1.0
	"Guardian Chance" = 1.0
	#Chance for mobs to be able to summon a flying mount
	#Range: 0.0 ~ 1.0
	"Phantom Chance" = 0.5

#Configs regarding mobs spawning with equipment
[equipment]
	#Blacklist items from whole mods. Add modid to prevent items from that mod being equipped. (For individual items use the equipment.json)
	"Item Blacklist" = ["cataclysm", "silentgear", "thermal", "twilightforest", "ad_astra", "mutantmore"]
	#Use blacklist as whitelist
	"Item Whitelist" = false
	#Blacklist for items mobs should never be able to use.
	#Use as in using the item similar to players (e.g. shooting bows)
	"Item Use Blacklist" = ["bigbrain:buckler"]
	#Turn the use blacklist into a whitelist
	"Item Use Whitelist" = false
	#Blacklist for specific mobs and items they shouldnt use (e.g. skeletons already use bows)
	#<entity registry name-item>
	#For different items but same entity use multiple lines
	#Some special names are BOW, TRIDEN, CROSSBOW refering to every bow/trident/crossbow item (So you dont need to type e.g. every bow item)
	"Entity Item Use Blacklist" = ["minecraft:drowned;TRIDENT", "minecraft:illusioner;BOW", "minecraft:piglin;CROSSBOW", "minecraft:pillager;CROSSBOW", "minecraft:skeleton;BOW", "minecraft:snow_golem;minecraft:snowball", "minecraft:stray;BOW", "minecraft:wither_skeleton;BOW"]
	#Base chance that a mob can have one piece of armor
	#Range: 0.0 ~ 1.0
	"Equipment Chance" = 0.005
	#Base chance for each additional armor pieces
	#Range: 0.0 ~ 1.0
	"Additional Equipment Chance" = 0.005
	#Adds additional x*difficulty% to base equip chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Equipment Addition" = 0.2
	#Chance for mobs to have a weapon
	#Range: 0.0 ~ 1.0
	"Weapon Chance" = 0.01
	#Adds additional x*difficulty% to base weapon chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Weapon Chance Add" = 0.2
	#Base chance for each armor pieces to get enchanted
	#Range: 0.0 ~ 1.0
	"Enchanting Chance" = 0.005
	#Adds additional x*difficulty% to base enchanting chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Enchanting Addition" = 0.1
	#Specify min and max enchanting levels according to difficulty. difficulty-minLevel-maxLevel
	"Enchanting Calc" = ["100-5-10", "200-5-15"]
	#Chance for mobs to have an item in offhand
	#Range: 0.0 ~ 1.0
	"Item Equip Chance" = 0.015
	#Adds additional x*difficulty% to base item chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Item Chance add" = 0.2
	#Should mobs drop the armor equipped through this mod? Will not change drops if the mob obtained the armor through other means (e.g. vanilla)
	"Should drop equipment" = false

#Settings for attribute modifiers
[attributes]
	#Health will be multiplied by difficulty*0.016*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Health Increase Multiplier" = 0.9
	#Health will be multiplied by at maximum this. Set to 0 means no limit
	#Range: 0.0 ~ 1.7976931348623157E308
	"Max Health Increase" = 5.0
	#Round health to the nearest x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Round HP" = 0.5
	#Damage will be multiplied by difficulty*0.008*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Damage Increase Multiplier" = 1.0
	#Damage will be multiplied by at maximum this. Set to 0 means no limit
	#Range: 0.0 ~ 1.7976931348623157E308
	"Max Damage Increase" = 3.0
	#Speed will be increased by difficulty*0.0008*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Speed Increase" = 0
	#Maximum increase in speed
	#Range: 0.0 ~ 1.0
	"Max Speed" = 0.1
	#Knockback will be increased by difficulty*0.002*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Knockback Increase" = 0
	#Maximum increase in knockback
	#Range: 0.0 ~ 1.0
	"Max Knockback" = 0.5
	#Magic resistance will be increased by difficulty*0.0016*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Magic Resistance Increase" = 0.2
	#Maximum increase in magic resistance. Magic reduction is percentage
	#Range: 0.0 ~ 1.0
	"Max Magic Resistance" = 0.4
	#Projectile Damage will be multiplied by 1+difficulty*0.008*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Projectile Damage Increase" = 1.0
	#Projectile damage will be multiplied by maximum of this
	#Range: 0.0 ~ 1.7976931348623157E308
	"Max Projectile Damage" = 3.0

