//priority: 997
ServerEvents.tags('item', event => {

    event.add('forge:bottles/blood', ['hexerei:blood_bottle', 'irons_spellbooks:blood_vial'])
    event.add('forge:steel_casings', 'kubejs:steel_casing')
    event.add('forge:shards/nether_star', 'silentgear:nether_star_fragment')
    event.add('forge:shards/nether_star', 'progressivebosses:nether_star_shard')

    event.add('forge:storage_blocks/cast_iron', 'createdeco:cast_iron_block')
    event.add('forge:storage_blocks/opal', 'dreamland:opal_block')
    event.add('forge:storage_blocks/precious_opal', 'dreamland:precious_opal_block')
    event.add('forge:storage_blocks/soul_steel', 'spirit:soul_steel_block')
    event.add('forge:storage_blocks', 'regions_unexplored:ash')
    event.add('forge:storage_blocks/ash', 'regions_unexplored:ash'),

    event.add('forge:gems/rose_quartz', 'cave_enhancements:rose_quartz')
    event.add('forge:ingots/stainless_steel', 'kubejs:stainless_steel_ingot')
    event.add('forge:ingots/chromium', 'kubejs:chromium_ingot')

    event.add('forge:chocolates', 'neapolitan:chocolate_bar', 'create:bar_of_chocolate')
    event.add('forge:chocolate_milkshakes', 'neapolitan:chocolate_milkshake')
    event.add('forge:chocolate_icecreams', 'neapolitan:chocolate_ice_cream')
    event.add('forge:strawberry_ice_creams', 'neapolitan:strawberry_ice_cream')
    event.add('forge:vanilla_ice_creams', 'neapolitan:vanilla_ice_cream')
    event.add('neapolitan:dried_vanilla_pods', 'neapolitan:dried_vanilla_pods')
    event.add('forge:fruits/pineapple', 'pineapple_delight:pineapple')
    event.add('forge:crops/vanilla', 'neapolitan:dried_vanilla_pods')
    event.add('forge:tuna', 'aquaculture:tuna')
    event.add('forge:juices/pineapple_juice', 'pineapple_delight:pineapple_juice')
    event.add('forge:juices/melon_juice', 'farmersdelight:melon_juice')
    event.add('forge:apple_pies', 'farmersdelight:apple_pie')
    event.add('forge:cheeseburgers', 'delightful:cheeseburger')
    event.add('forge:hamburgers', 'farmersdelight:hamburger')
    event.add('forge:doughs', 'create:dough')
    event.add('forge:noodles', 'farmersdelight:raw_pasta')
    event.add('forge:blts', 'farmersdelight:bacon_sandwich')
    event.add('forge:milk/milk_bottle', ['neapolitan:milk_bottle', 'productivebees:milk_bottle', 'hexerei:milk_bottle'])
    event.add('forge:milks', 'farmersdelight:milk_bottle')
    event.add('forge:crops/coffeebean', 'farmersrespite:coffee_berries')
    event.add('forge:coffee_beans', 'createcafe:roasted_coffee_beans')
    event.add('forge:cheese', 'gourmet:cheese')
    event.add('forge:ice_cubes', 'gourmet:ice_cube')
    event.add('forge:raw_bacon', 'gourmet:raw_bacon')
    event.add('forge:cooked_bacon', 'gourmet:cooked_bacon')
    event.add('forge:ground_beef', 'farmersdelight:minced_beef'),
    event.add('forge:beef_patty', 'farmersdelight:beef_patty')
    event.add('forge:storage_blocks/carrot', ['thermal:carrot_block', 'farmersdelight:carrot_crate'])
    event.add('forge:storage_blocks/potato', ['thermal:potato_block', 'farmersdelight:potato_crate'])
    event.add('forge:storage_blocks/beetroot', ['thermal:beetroot_block', 'farmersdelight:beetroot_crate'])

    event.add('forge:tools/scavenging', "minecraft:wooden_sword")

    event.add('silentgear:starlight_charger_catalysts', ['waystones:warp_dust', 'silentgear:nether_star_fragment'])
    event.add('silentgear:starlight_charger_catalysts/tier1', 'waystones:warp_dust')
    event.add('silentgear:starlight_charger_catalysts/tier2', 'silentgear:nether_star_fragment')

    event.add('alexsmobs:mungus_spawns', 'dreamland:white_mold')
    event.add('alexsmobs:crimson_mosquito_spawns', 'dreamland:white_mold')
    event.add('alexsmobs:tarantula_hawk_spawns', 'dreamland:white_mold')
    event.add('alexsmobs:cockroach_spawns', 'dreamland:white_mold')
    event.add('alexsmobs:fly_spawns', 'dreamland:white_mold')

    event.remove('silentgear:starlight_charger_catalysts', ['silentgear:blaze_gold_dust', 'silentgear:azure_silver_dust'])
    event.remove('silentgear:starlight_charger_catalysts/tier1', 'silentgear:blaze_gold_dust')
    event.remove('silentgear:starlight_charger_catalysts/tier2', 'silentgear:azure_silver_dust')
    event.remove('supplementaries:chocolate_bars', 'neapolitan:chocolate_bar')
    event.remove('forge:fruits/lime', 'minecraft:slime_ball')
})